package com.mooracle.review;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) //<-auto generated by Spring JPA
    private final Long id; // since it is final it needs to be initialized-> use Constructor for that

    // TODO: we are duplicating with all @Entity
    private int rating;
    private String description;

    protected Review() {
        id = null;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
